version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: meu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: livraria_db
      MYSQL_USER: livraria_user
      MYSQL_PASSWORD: senha123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  livraria:
    build: .
    container_name: livraria
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/livraria_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: livraria_user
      SPRING_DATASOURCE_PASSWORD: senha123
    ports:
      - "8080:8080"

volumes:
  mysql_data:

