# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAnalise():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def acessar_pagina(self):
    self.driver.get("http://localhost:8080/login")
    self.driver.set_window_size(1600, 864)
    time.sleep(4)
    self.driver.find_element(By.CSS_SELECTOR, ".client-item:nth-child(1) button").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Análise de Categorias").click()
    time.sleep(1)

  def testar_grafico(self):
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#lista-livros > label:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#lista-livros > label:nth-child(6)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#lista-livros > label:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#lista-categorias > label:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#lista-categorias > label:nth-child(5)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#lista-categorias > label:nth-child(3)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(4)
    self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#lista-livros > label:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#lista-livros > .filtro-input").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#lista-livros > .filtro-input").send_keys("19")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "#lista-livros > label:nth-child(7) > input").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "startDate").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "startDate").send_keys("2025-04-29")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".container").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(4)
    self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(1)
    self.driver.find_element(By.ID, "graficoVendas").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "graficoVendas").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "graficoVendas").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "graficoVendas").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "startDate").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "startDate").send_keys("2025-01-29")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(3)
    self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(1)
    self.driver.find_element(By.ID, "startDate").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "startDate").send_keys("2020-01-29")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(3)
    self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(2)
    self.driver.find_element(By.ID, "startDate").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "startDate").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "startDate").send_keys("2015-01-29")
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(1)
    self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)
    self.driver.find_element(By.ID, "startDate").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "startDate").send_keys("2028-01-29")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(1)
    assert self.driver.switch_to.alert.text == "A data de início não pode ser posterior à data de fim."
    self.driver.switch_to.alert.accept()
    time.sleep(2)
    self.driver.find_element(By.ID, "startDate").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "startDate").send_keys("1914-01-29")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".container").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(1)
    assert self.driver.switch_to.alert.text == "A data de início não pode ser anterior a 01/01/2010."
    self.driver.switch_to.alert.accept()
    time.sleep(4)

  def main(self):
    self.acessar_pagina()
    self.testar_grafico()

# Para rodar os testes
if __name__ == "__main__":
    test = TestAnalise()
    test.setup_method(None)
    try:
        test.main()
    finally:
        test.teardown_method(None)
  
